# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infant_tracker', '0004_auto_20160126_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WKE', 'Woke'), ('NRS', 'Nursed'), ('NPD', 'Napped'), ('BTL', 'Bottle'), ('ACT', 'Activity'), ('BED', 'Bedtime')], default=1, max_length=3, verbose_name='What Happened'),
        ),
    ]
